version: '2.13'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: